### ISSUE TITLE
This is too awesome!!

### ISSUE THREAD

**Issue by codexetreme** [alfredalpaca/setup#2]
I like this setup its very clean and nice ! 

I think you can symlink files instead of copy pasting that way changes are instantaneous :) 

But awesome :)

PS: already forked :P

**Comment by alfredalpaca** [comment]
Symlink which files? I dont follow

**Comment by codexetreme** [comment]
The gitconfig.sh 

It copies over the gitconfig from the repo to its correct place. Instead you can symlink it.

**Comment by alfredalpaca** [comment]
Done. Also brought the `user` blocks into this repo to remove the dependency of it being in `.config`
